// Every word the interface shows, in English and Hindi. Nothing here tells anyone what to do with a stock:
// the product looks backward only.

export const en = {
  nav: { reckon: "Reckon a channel", method: "How it is checked", lang: "हिंदी" },
  status: { prices: "Prices", to: "to", lag: "30-day lag" },

  hero: {
    eyebrow: "The record a tip channel never posts",
    // [text, set in red italics]
    title: [
      ["Every tip channel has a day of ", false],
      ["reckoning.", true],
    ] as [string, boolean][],
    lead: "Yours comes before you pay for it.",
    placeholder: "channel name or link",
    go: "Reckon it",
    or: "or bring",
    sources: { export: "Telegram export", whatsapp: "WhatsApp chat", shots: "Screenshots", paste: "Paste messages" },
    promise: ["No account", "Chats stay on your device", "Looks at the past only"],
    badLink: "That does not look like a public channel link. Try t.me/channelname.",
  },

  replay: {
    sample: "A real public channel · name withheld",
    subscribers: "subscribers",
    reading: "reading",
    ledger: "Ledger",
    rule: "₹10,000 in every call · one lot minimum · first target or expiry",
    balance: "Account",
    cols: { date: "Date", contract: "Contract", in: "In", out: "Out", result: "Result", net: "Net" },
    stamps: { target: "Target", expired: "Expired", zero: "Expired at zero", stop: "Stop-loss", horizon: "Closed", open: "Open", unverifiable: "Could not check", "no-funds": "No money left", "not-triggered": "Never triggered" },
    lots: "lot",
    verdictA: "could not pay for the next call",
    verdictDays: (n: number) => `${n} days`,
    summary: (taken: number, zero: number, brags: number, losses: number) =>
      `${taken} calls taken. ${zero} expired at zero. In the same week the channel posted ${brags} profit messages and ${losses === 0 ? "not one about a loss" : `${losses} about a loss`}.`,
    slPaid: "The stop-loss was behind a paywall.",
    full: "Open the full reckoning",
    again: "Replay",
    peak: "peak",
    source: (to: string) => `Exchange prices: NSE and BSE daily bhavcopy to ${to}. Costs included.`,
    exhibit: "Exhibit A · the ledger",
    exhibitSub: (subs: string) => `A real channel, ${subs} subscribers. ₹10,000 in every call.`,
    inDays: (n: number) => `in ${n} days`,
    dependsShort: "Depends on reading",
    range: (n: number, lo: string, hi: string) => `${n} of these results depend on how the day's prices are read. Across the three readings the week ends between ${lo} and ${hi}.`,
    listen: "Listen",
    stopListening: "Stop",
    // every figure arrives already written out in words (see lib/say.ts)
    spoken: (n: { subs: string; start: string; stake: string; end: string; days: string; taken: string; zero: string; brags: string }) =>
      `A real tip channel, with ${n.subs} subscribers. ${n.start} rupees, put ${n.stake} at a time into every call it posted, became ${n.end} rupees in ${n.days} days. ${n.taken} calls were taken. ${n.zero} expired at zero. In the same week, the channel posted ${n.brags} messages about profit, and not one about a loss. The stop-loss was behind a paywall.`,
  },

  report: {
    stages: { messages: "Reading the channel", prices: "Fetching exchange prices", replaying: "Replaying calls" },
    readSoFar: (n: number, back: string) => `${n.toLocaleString("en-IN")} messages read, back to ${back}`,
    replayed: (a: number, b: number) => `${a} of ${b} calls replayed`,
    noSource: "Bring a channel to reckon",
    noSourceBody: "Paste a public Telegram channel, open an export, or start with the sample below.",
    trySample: "Open the sample channel",
    previewOff: "This channel has its public preview switched off, so it cannot be read from a link. Export the chat from Telegram Desktop and open the file instead.",
    noCalls: "No calls could be read in these messages.",
    noCallsBody: (n: number, images: number) => `${n} messages were read. ${images} of them are pictures with no text, which this build cannot read.`,
    failed: "Something went wrong while reckoning.",
    messages: "messages",
    period: (a: string, b: string) => `${a} to ${b}`,

    account: "The account",
    accountRule: (stake: string) => `${stake} in every call, one lot minimum`,
    ranOut: (date: string, n: number) => `Could not pay for a call from ${date}, after ${n} calls`,
    afterCalls: (n: number) => `after ${n} calls`,
    band: "Across the three readings it ends between",
    bandWorst: "and",
    bandWhy: "Daily prices cannot show whether a price was touched before or after a message. The main figure counts a doubtful win only when the channel announced it at the time.",
    paperOnly: "A paper record: every call taken at the quoted price, the same stake each time, held to its first target, stop-loss or expiry. It says nothing about the next call.",

    record: "The record",
    recordSub: (checked: number, calls: number) => `${checked} of ${calls} calls could be replayed on exchange prices`,
    classes: { target: "Reached target", stop: "Stop-loss hit", expired: "Expired", worthless: "Expired at zero", horizon: "Closed, no level hit", open: "Still open" },
    hitRate: "Reached target",
    byChance: "A coin would manage",
    byChanceWhy: "If prices moved with no direction at all, calls with these targets and stop-losses would reach target this often. A hit rate near this number shows no skill.",
    flat: "Same stake in every replayed call",
    flatSub: (n: number, stake: string) => `${stake} × ${n} calls, costs included`,
    meanReturn: "Average result per call",

    unchecked: "Not checked",
    codes: {
      "too-recent": "Too recent: price data is kept 30 days behind",
      "before-data": "Older than the price data",
      "off-exchange": "Trades on an exchange outside the data",
      "unknown-instrument": "Stock or contract not found",
      "not-traded": "Contract did not trade that day",
      "price-mismatch": "Quoted price never traded that day",
      "no-entry": "Intraday call with no entry price",
      "level-not-reached": "Entry level never reached",
      "low-confidence": "Read with low confidence, left out",
      "no-funds": "Account had no money left",
    },
    unread: (n: number) => `${n} messages looked like calls but named no stock or contract that could be read`,
    images: (n: number) => `${n} messages are pictures with no text`,

    sections: { ledger: "Ledger", said: "What it said afterwards", selling: "Selling", registration: "Registration", pause: "Pause", method: "How this was checked" },
    pause: "Before the next call",

    ledger: "Every call, settled",
    filters: { all: "All", target: "Target", lost: "Lost", doubtful: "Depends on reading", unchecked: "Not checked" },
    cols: { date: "Date", call: "Call", inOut: "In → out", result: "Result", net: "Net", balance: "Account" },
    depends: "depends on reading",
    showMore: (n: number) => `Show ${n} more`,
    detail: {
      message: "The message",
      checked: "How it was checked",
      contract: "Replayed on",
      entered: "Entered",
      exited: "Exited",
      basis: { stated: "at the quoted price", trigger: "when the entry level traded", open: "at the opening price", close: "at the closing price" },
      exitBasis: { target: "at the first target", stop: "at the stop-loss", "gap-open": "at the open, past the level", close: "at the close", "next-open": "at the next open", settlement: "at expiry value", "last-price": "at the last traded price" },
      other: "Other readings",
      best: "Best for the channel",
      worst: "Worst for the channel",
      lots: (lots: number, qty: number) => `${lots} lot${lots > 1 ? "s" : ""} (${qty} units)`,
      shares: (qty: number) => `${qty} shares`,
      costs: "costs",
      notes: "Read from the message",
    },

    said: "What the channel said afterwards",
    saidWinners: (a: number, b: number) => `${a} of ${b} winning calls got a victory post`,
    saidLosers: (a: number, b: number) => `${a} of ${b} losing calls were ever mentioned again`,
    saidAdmitted: (a: number) => (a === 0 ? "Not one post admits a stop-loss or a loss" : `${a} posts admit a stop-loss or a loss`),
    saidUnsupported: (n: number) => `${n} "target hit" posts where the target price had not traded`,
    saidImpossible: (n: number) => `${n} posts quote a price the contract never traded at`,
    saidClaim: (pct: number) => `The channel's own claim: ${pct}% accuracy`,
    claimed: "claimed",
    reached: "furthest it traded",

    selling: "What the messages are for",
    sellingSub: (a: number, b: number) => `${a} of ${b} messages sell something`,
    cues: {
      "paid-group": "Paid or premium group",
      payment: "Payment links and UPI ids",
      contact: "\"Message me\" and phone numbers",
      "join-link": "Links into other groups",
      guarantee: "Guarantees and sure shots",
      "profit-brag": "Profit figures and screenshots",
      urgency: "Hurry, limited seats",
      "account-handling": "Offers to trade your account",
      "paywalled-levels": "Stop-loss or target held back for payment",
    },

    registration: "SEBI registration",
    regNone: "The channel shows no SEBI registration number. Giving buy and sell calls for a fee requires registration as a Research Analyst or Investment Adviser.",
    regOn: (no: string, name: string) => `${no} is on SEBI's register as "${name}".`,
    regOnWarn: "A real number does not prove the channel belongs to that person: registered names are often impersonated. Check the name against the channel.",
    regOff: (no: string) => `${no} is not on SEBI's register.`,
    regAsOf: (date: string) => `Register copied from sebi.gov.in on ${date}`,
    routeUnreg: "To report an unregistered channel: SEBI's Market Intelligence portal (mi.sebi.gov.in). If money was lost: cybercrime.gov.in or call 1930.",
    routeReg: "A complaint against a registered analyst goes to SCORES (scores.sebi.gov.in).",

    verdict: {
      tag: "In plain words",
      headBehind: (start: string, end: string) => `${start} became ${end}.`,
      headAhead: "Ahead on paper. That is not a reason to pay.",
      headNothing: "Too soon to replay these calls.",
      stake: (stake: string) => `${stake} went into every call the channel posted.`,
      broke: (n: string) => `After ${n} calls there was not enough left to take the next one.`,
      aheadFigure: (start: string, end: string) => `On paper, ${start} became ${end}.`,
      paper: "That figure takes every call at the quoted price, the moment it was posted. A follower gets in later, at a worse price.",
      range: (lo: string, hi: string) => `Read the day's prices another way and the same calls end between ${lo} and ${hi}.`,
      hit: (hit: string, coin: string) => `Targets were reached ${hit} of the time. Chance alone, with the same targets and stop-losses, would reach ${coin}.`,
      paywalled: (n: string, one: boolean) => (one ? "The stop-loss was held back for payment." : `In ${n} calls the stop-loss was held back for payment.`),
      noStop: (n: string, m: string) => `${n} of ${m} calls gave no stop-loss.`,
      admitted: (lost: string, n: string) => `${lost} calls lost money. Posts that admit a loss: ${n}.`,
      unsupported: (n: string) => `${n} result posts quote a price the contract had not traded at.`,
      regNone: "The channel shows no SEBI registration number.",
      regOn: "It shows a number that is on SEBI's register. Check that the channel really belongs to that name.",
      regOff: "It shows a registration number that is not on SEBI's register.",
      selling: (a: string, b: string) => `${a} of ${b} messages sell something.`,
      promise: (words: string) => `The messages say ${words}. No one can promise a result in the market.`,
      tooRecent: "Price data is kept 30 days behind, so calls from the last month cannot be replayed yet.",
      cannot: "These calls could not be matched to exchange prices.",
      fno: "SEBI's own study found that 9 in 10 individual traders in equity futures and options lost money.",
      next: "None of this says what the next call will do.",
      percent: "percent",
      rupees: "rupees",
      noReplay: "No call could be replayed yet",
    },

    whatIf: {
      nav: "What if",
      title: "The same calls, with your money",
      lead: "Move the sliders. The same calls replay on the same exchange prices; only the money changes.",
      capital: "Money you start with",
      stake: "Share put into each call",
      borrowed: "Share that is borrowed",
      perCall: (amount: string) => `${amount} in every call`,
      borrowedOf: (amount: string) => `${amount} of it borrowed`,
      loanNote: (rate: number) => `Borrowed money is charged ${rate}% a month, the range of an instant app loan.`,
      ends: "The account ends at",
      ranOut: (date: string, n: number) => `Could not pay for a call from ${date}, after ${n} calls`,
      taken: (n: number) => `${n} calls taken`,
      fall: "Deepest fall from a peak",
      owed: "Owed to the lender at the end",
      ownGone: (date: string) => `Your own money was gone by ${date}`,
      ownKept: "The balance never fell below what was borrowed",
      netWorth: "Left after repaying the loan",
      presets: { savings: "Savings only", half: "Half borrowed", all: "Everything in each call" },
    },

    flags: {
      nav: "Patterns",
      title: "Patterns around the calls",
      lead: "Shapes in price and volume around each call, measured on the exchange's own files. A pattern is not a finding: it shows what happened, not why.",
      none: "None of these patterns appear around this channel's calls.",
      kinds: {
        "pump-shape": ["Jumped, then fell back", "Up sharply on heavy volume within two days of the call, then well down from the peak within ten."],
        spike: ["Jumped on heavy volume", "Up sharply on several times the normal volume within two days of the call."],
        "pre-run": ["Already running before the call", "Price and volume had jumped in the five trading days before the call."],
        "sme-board": ["SME-platform stocks", "Listed on the SME platform, where a small amount of buying moves the price."],
        thin: ["Thinly traded stocks", "Very little money changes hands in these on a normal day."],
        "expiry-day": ["Options bought on expiry day", "Bought on the contract's last day, when an option can lose its whole value within hours."],
      },
      calls: (n: number) => `${n} call${n === 1 ? "" : "s"}`,
      more: (n: number) => `and ${n} more`,
    },

    complaint: {
      nav: "Report it",
      title: "Report this channel",
      leadUnreg: "The channel shows no SEBI registration that could be confirmed. Information about unregistered advice goes to SEBI's Market Intelligence portal. The draft below is filled in from this report: read it, correct it, add what you know.",
      leadReg: "The channel shows a number that is on SEBI's register. If it is run by that analyst, a complaint goes to SCORES. If it only uses the number, that is for the Market Intelligence portal. The draft below is filled in from this report.",
      draftNote: "The draft is in English.",
      copy: "Copy the draft",
      copied: "Copied",
      csv: "Download the call list (CSV)",
      print: "Print the evidence sheet, or save it as PDF",
      open: (site: string) => `Open ${site}`,
      note: "Nothing is sent from here. You file it yourself, with your own screenshots.",
      sheet: "Evidence sheet",
      generated: (date: string) => `Prepared on ${date} from the channel's messages and the NSE and BSE daily price files. Results that depend on the order of prices within a day are marked. Where a message names no expiry, the nearest expiry in which the quoted entry price traded was used.`,
    },

    method: "How this was checked",
    methodPoints: [
      "Prices are the exchanges' own daily files (NSE and BSE bhavcopy): open, high, low and close of the exact contract.",
      "A call is entered at its quoted price only if that price traded that day. It ends at the first target, the stop-loss, or expiry.",
      "A daily file cannot show whether a price came before or after a message. So every call is read three ways, and the results that depend on the reading are marked.",
      "Price data is kept 30 days behind today, as SEBI requires of tools that use market prices for investor education.",
    ],
    methodMore: "The full rules",
  },

  method: {
    title: "How a call is checked",
    lead: "Every rule the ledger applies, in the order it applies them. Nothing here is a judgement: it is arithmetic on the exchange's own prices.",
    rulesTitle: "The rules",
    rules: [
      ["Reading the message", "A message counts as a call when a stock or contract and at least one price can be read from it. The reader is a fixed set of rules, not a language model, so the same message always reads the same way. Messages it cannot read are counted and shown, never guessed."],
      ["Finding the contract", "An option is matched to its exact strike, type and expiry. With no expiry in the message, the nearest expiry on or after the call date is used; if the quoted price does not fit that contract's prices for the day, the next expiry that fits is used instead."],
      ["Entering", "The call is entered at the price the message quotes, but only if that price traded that day. \"Buy above 250\" starts when 250 trades. A quoted price outside the day's range means the call cannot be checked."],
      ["Leaving", "The call ends at its first target or its stop-loss, whichever the prices reach first. With neither, an option is held to expiry and settled at its value against the index or stock; a share is closed after ten trading days."],
      ["Money", "₹50,000 to start. ₹10,000 goes into each call: whole lots for options and futures, at least one. Brokerage, STT and exchange charges are taken off with a simple, stated model. When the account cannot pay for one lot, the call is not taken."],
    ],
    readingsTitle: "Three readings of the same day",
    readingsBody: "The exchange's daily file gives the day's open, high, low and close, not the order they came in. On the day a call is posted, the high may have printed before the message. So each call is replayed three ways.",
    readings: [
      ["Best", "Every doubtful touch is read in the channel's favour. No single call can have done better than this."],
      ["Worst", "A price counts only if it must have traded after the entry: the day closed beyond it, or the message came at the open and the price lies outside the open and the quoted entry."],
      ["Main figure", "A doubtful win counts when the channel announced it at the time and that day's prices do not contradict it. A doubtful stop-loss counts when the channel stayed silent."],
    ],
    chanceTitle: "The coin's hit rate",
    chanceBody: "A target 25% away with no stop-loss is reached about four times in five by a price that moves at random, because the only way to miss is to fall to zero first. The ledger works this out for the channel's own calls: for each, (entry − stop) ÷ (target − stop), with the stop at zero when none is given. A hit rate near that figure shows no skill. What matters then is what the misses cost.",
    dataTitle: "Where the numbers come from",
    data: [
      ["Share prices", "NSE cash-market bhavcopy, every trading day from 1 January 2024."],
      ["Options and futures", "NSE F&O bhavcopy, and BSE derivatives bhavcopy for SENSEX and BANKEX contracts."],
      ["Splits and bonuses", "Found from the price gap on the day they take effect; later prices are restated in the call's terms."],
      ["SEBI registration", "A dated copy of SEBI's public register of Research Analysts and Investment Advisers."],
      ["30-day lag", "Price data stops 30 days before the day the data was built. SEBI allows market prices in investor education only with that lag, so the newest calls show as too recent."],
    ],
    limitsTitle: "What it cannot do",
    limits: [
      "It cannot see inside a trading day. Results that depend on the order of prices within the day are marked, and the account is given as a range.",
      "It cannot read calls posted as pictures.",
      "It has no prices for commodities, currencies, crypto or foreign markets, and says so for each such call.",
      "It cannot read a channel whose public preview is switched off, except from an export file.",
      "Stock option contracts are not restated across a split or bonus.",
      "It cannot tell whether a follower could actually have bought at the quoted price, or how late they saw the message.",
      "Its reasons for each call's result are written in English only.",
      "It says nothing about what any stock or contract will do next, and never will.",
    ],
  },
  landing: {
    rail: ["The ledger", "One call", "The coin test", "The chat", "Three readings", "The pause", "Where to report"],
    scroll: "The evidence, exhibit by exhibit",

    oneCall: {
      tag: "Exhibit B · one call",
      title: "What the message said. What the exchange recorded.",
      step1: (date: string, time: string) => `${date} · ${time} · the message`,
      note1: "No stop-loss in the message. It is sold separately.",
      step2: "The same contract, day by day",
      target: "target",
      bought: "bought",
      expiry: "expiry",
      before: "before the call",
      step3: (date: string) => `${date} · settlement`,
      note3: (entry: string, target: string) => `Bought at ${entry}. Never reached ${target}. Expired at zero.`,
      sum: (qty: number, entry: string, costs: string) => `${qty} units × ₹${entry}, plus ${costs} in costs`,
    },

    coin: {
      tag: "Exhibit C · the coin test",
      title: "Would a coin have done better?",
      lead: "A target with no stop-loss is reached about three times in four by chance alone. A hit rate means nothing until it stands beside what a coin would manage with the same targets and stop-losses.",
      result: (below: number, total: number) => `${below} of ${total} real channels reached their targets less often than the coin.`,
      resultBest: (n: number) => `${n} stay below it even when every doubtful result is read in the channel's favour.`,
      xAxis: "what a coin would hit with the same targets and stop-losses →",
      yAxis: "what the channel hit →",
      diagonal: "as good as a coin",
      above: "Exhibit A",
      whisker: "dot: main figure · line: worst to best reading",
      foot: (read: number, total: number, min: number) => `${read} public channels read. The ${total} with ${min} or more replayed calls that carried a target are shown. Names withheld.`,
      caveat: "Beating the coin is not the same as making money. What the misses cost decides that.",
    },

    chat: {
      tag: "Exhibit D · the chat",
      title: (n: string) => `${n} messages. Not one about a loss.`,
      lead: "Every message the same channel posted, in the order it posted them. One square each.",
      kinds: { call: "calls", profit: "posts about points and profit", selling: "sales messages", loss: "posts about a loss", other: "everything else" },
      won: (a: number, b: number) => `${a} of ${b} winning calls were followed by a profit post`,
      lost: (a: number, b: number) => `${b} calls lost money. Posts that say so: ${a}`,
      stop: (a: number, b: number) => `${a} of ${b} calls gave no stop-loss. The message said "SL PAID"`,
    },

    readings: {
      tag: "Exhibit E · what a daily price cannot settle",
      title: "One day. Three honest readings.",
      lead: (date: string, time: string, contract: string, target: string) => `${date}, ${time}. The channel calls ${contract} with a target of ${target}. The exchange's file for that day gives the high as exactly ${target}.`,
      question: (time: string) => `Before ${time}, or after? A daily file does not say.`,
      bar: "the day's bar",
      ohlc: { o: "open", h: "high", l: "low", c: "close" },
      message: "message",
      pathA: "the high came before the message",
      pathB: "the high came after the message",
      illustration: "Two days that leave the same bar. The paths are drawn for illustration; the bar is the exchange's.",
      rows: {
        best: ["Best for the channel", "Every doubtful touch counts as reached."],
        worst: ["Worst for the channel", "A price counts only if it must have come after the call."],
        likely: ["Main figure", "A doubtful win counts only if the channel announced it at the time."],
      },
      quoted: (q: string) => `The channel's own updates that morning stopped at ${q}.`,
      close: "Every result like this is marked on the ledger, and the account is given as a range.",
    },

    pause: {
      tag: "Exhibit F · before the next call",
      title: "Twenty-four hours between the message and the money.",
      lead: "A tip arrives with a clock on it: now, fast, limited seats. The pause card sets a slower clock beside it.",
      lookFor: "Three things to look for in the message",
      questions: ["Is the stop-loss in the message, or sold separately?", "Is the sender on SEBI's register?", "What became of the last ten calls?"],
      card: "Pause card",
      record: "The channel's record",
      hit: (a: string, b: string) => `Reached target ${a} of the time. A coin would: ${b}.`,
      admitted: (lost: number, n: number) => `${lost} calls lost money. Posts that say so: ${n}.`,
      noStop: "The stop-loss is sold separately.",
      reasonLabel: "Why do you want to take this call?",
      placeholder: "Write it in your own words",
      start: "Start the 24 hours",
      running: "Read your reason again in",
      done: "24 hours have passed. Read your reason again.",
      reset: "Clear",
      saved: "Kept on this device only. Nothing is sent anywhere.",
    },

    where: {
      tag: "Exhibit G · where to report it",
      title: "Unregistered advice has an address.",
      lead: "Giving buy and sell calls for a fee needs a SEBI registration. Check the number a channel shows, then take the route that fits.",
      checkLabel: "Check a registration number",
      placeholder: "INH… or INA… number",
      check: "Check",
      bad: "A registration number looks like INH000001234 or INA000001234.",
      found: (no: string, name: string, from: string) => `${no} is on SEBI's register as "${name}", registered ${from}.`,
      notFound: (no: string) => `${no} is not on SEBI's register.`,
      asOf: (date: string) => `Register copied from sebi.gov.in on ${date}`,
      loading: "Opening the register",
      routes: [
        ["The channel is not registered", "SEBI Market Intelligence portal", "mi.sebi.gov.in", "https://mi.sebi.gov.in/"],
        ["Money has already been lost", "National Cyber Crime Reporting Portal, or call 1930", "cybercrime.gov.in", "https://cybercrime.gov.in/"],
        ["A registered analyst or adviser", "SEBI SCORES", "scores.sebi.gov.in", "https://scores.sebi.gov.in/"],
      ] as [string, string, string, string][],
      if: "If",
    },


    closing: {
      title: "Bring the channel you are about to pay for.",
      foot: "Reckoning looks at the past only. It says nothing about what any stock or contract will do next.",
      sources: "Prices: NSE and BSE daily bhavcopy. Register: sebi.gov.in.",
    },
  },
  caseFile: {
    nav: "A SEBI case",
    tag: "Case file",
    title: "The same checks, on a case SEBI has already examined.",
    lead: (date: string) => `On ${date} SEBI passed an interim order about stock recommendations posted on social media. Annexure A of the order lists the recommendations behind the money it impounded. We ran this site's pattern checks on those dates, and on ordinary days in the same stocks.`,
    caution: "An ex-parte interim order records what SEBI found on a first view. It is not a final finding against anyone, and no person is named on this page.",
    orderRef: "Order",
    impounded: "Impounded by the order",
    recos: "Recommendations in Annexure A",
    measured: "Inside our price files",
    coverage: (measured: number, total: number, stocks: number, from: string) => `${measured} of the ${total} recommendations, in ${stocks} stocks, fall inside our price files (NSE, from ${from}). The rest are in stocks that trade only on BSE, or are older than the data.`,
    ratesTitle: "How often each pattern appears",
    onRecos: "after the order's recommendations",
    onOrdinary: "on ordinary days in the same stocks",
    patterns: {
      spike: ["Jumped on heavy volume", "Up 8% or more within two trading days, on three times normal volume or more."],
      pump: ["Jumped, then fell back", "The same jump, followed by a fall of 15% or more from the peak within ten trading days."],
      preRun: ["Already running before the post", "Up 10% or more in the five trading days before, on three times normal volume or more."],
      thin: ["Thinly traded", "Less than ₹25 lakh changing hands on a normal day."],
    },
    times: (x: string) => `${x} times as often`,
    notMore: "No more often than on ordinary days. This check did not pick these stocks out.",
    smeLine: (n: number, total: number) => `${n} of the ${total} measured recommendations were in SME-platform stocks.`,
    chartsTitle: "Three of the stocks",
    chartsLead: "Closing price and volume. Each red line is a recommendation listed in the order.",
    recoCount: (n: number) => `${n} recommendations`,
    tableTitle: "Every recommendation measured",
    cols: { day: "First trading day", stock: "Stock", up: "Up within 2 days", volume: "Volume", fall: "Then fell", marks: "Patterns" },
    sme: "SME",
    showAll: (n: number) => `Show all ${n}`,
    source: "Source: SEBI order, Annexure A, pages 198 to 234. Prices: NSE daily bhavcopy.",
    openOrder: "Open the order on sebi.gov.in",
  },
};

export type Strings = typeof en;

export const hi: Strings = {
  nav: { reckon: "चैनल का हिसाब", method: "जाँच कैसे होती है", lang: "English" },
  status: { prices: "भाव", to: "तक", lag: "30 दिन पीछे" },

  hero: {
    eyebrow: "वह हिसाब जो टिप चैनल कभी नहीं दिखाता",
    title: [
      ["हर टिप चैनल का एक दिन ", false],
      ["हिसाब", true],
      [" होता है।", false],
    ] as [string, boolean][],
    lead: "आपका हिसाब, पैसा लगाने से पहले।",
    placeholder: "चैनल का नाम या लिंक",
    go: "हिसाब देखें",
    or: "या लाइए",
    sources: { export: "टेलीग्राम एक्सपोर्ट", whatsapp: "व्हाट्सऐप चैट", shots: "स्क्रीनशॉट", paste: "मैसेज पेस्ट करें" },
    promise: ["कोई खाता नहीं", "चैट आपके फ़ोन में ही रहती है", "सिर्फ़ बीता हुआ देखता है"],
    badLink: "यह सार्वजनिक चैनल का लिंक नहीं लगता। t.me/channelname लिखकर देखिए।",
  },

  replay: {
    sample: "एक असली सार्वजनिक चैनल · नाम छिपाया गया",
    subscribers: "सदस्य",
    reading: "पढ़ रहा है",
    ledger: "बही",
    rule: "हर कॉल में ₹10,000 · कम से कम एक लॉट · पहला टारगेट या एक्सपायरी",
    balance: "खाता",
    cols: { date: "तारीख़", contract: "कॉन्ट्रैक्ट", in: "ख़रीद", out: "निकास", result: "नतीजा", net: "नफ़ा/नुक़सान" },
    stamps: { target: "टारगेट", expired: "एक्सपायर", zero: "शून्य पर ख़त्म", stop: "स्टॉप-लॉस", horizon: "बंद", open: "खुला", unverifiable: "जाँच नहीं हो सकी", "no-funds": "पैसा नहीं बचा", "not-triggered": "शुरू ही नहीं हुई" },
    lots: "लॉट",
    verdictA: "अगली कॉल के लिए पैसा नहीं बचा",
    verdictDays: (n: number) => `${n} दिन`,
    summary: (taken: number, zero: number, brags: number, losses: number) =>
      `${taken} कॉल ली गईं। ${zero} शून्य पर ख़त्म हुईं। उसी हफ़्ते चैनल ने मुनाफ़े के ${brags} मैसेज डाले, घाटे ${losses === 0 ? "का एक भी नहीं" : `के ${losses}`}।`,
    slPaid: "स्टॉप-लॉस पैसे देने पर ही मिलता था।",
    full: "पूरा हिसाब खोलें",
    again: "दोबारा चलाएँ",
    peak: "सबसे ऊपर",
    source: (to: string) => `एक्सचेंज के भाव: NSE और BSE की रोज़ की भावकॉपी, ${to} तक। ख़र्च शामिल।`,
    exhibit: "प्रमाण क · बही",
    exhibitSub: (subs: string) => `एक असली चैनल, ${subs} सदस्य। हर कॉल में ₹10,000।`,
    inDays: (n: number) => `${n} दिन में`,
    dependsShort: "पढ़ने पर निर्भर",
    range: (n: number, lo: string, hi: string) => `इनमें से ${n} नतीजे इस पर निर्भर हैं कि दिन के भाव कैसे पढ़े जाएँ। तीनों तरह से पढ़ने पर हफ़्ता ${lo} और ${hi} के बीच ख़त्म होता है।`,
    listen: "सुनिए",
    stopListening: "रोकें",
    // कही जाने वाली पंक्तियों में "गईं", "हुईं" जैसे अनुनासिक अंत नहीं रखे गए: रिकॉर्ड की गई आवाज़ उन्हें ठीक नहीं बोलती
    spoken: (n: { subs: string; start: string; stake: string; end: string; days: string; taken: string; zero: string; brags: string }) =>
      `एक असली टिप चैनल, जिसके ${n.subs} सदस्य हैं। ${n.start} रुपये, हर कॉल में ${n.stake} लगाकर, ${n.days} दिन में ${n.end} रुपये रह गए। ${n.taken} कॉल में पैसा लगा। उनमें से ${n.zero} का दाम शून्य हो गया। उसी हफ़्ते चैनल ने मुनाफ़े के ${n.brags} मैसेज डाले, और घाटे का एक भी नहीं। स्टॉप-लॉस पैसे देने पर ही मिलता था।`,
  },

  report: {
    stages: { messages: "चैनल पढ़ा जा रहा है", prices: "एक्सचेंज के भाव आ रहे हैं", replaying: "कॉल दोबारा चलाई जा रही हैं" },
    readSoFar: (n: number, back: string) => `${n.toLocaleString("en-IN")} मैसेज पढ़े, ${back} तक`,
    replayed: (a: number, b: number) => `${b} में से ${a} कॉल चलाई गईं`,
    noSource: "हिसाब के लिए चैनल लाइए",
    noSourceBody: "कोई सार्वजनिक टेलीग्राम चैनल डालिए, एक्सपोर्ट फ़ाइल खोलिए, या नीचे दिए नमूने से शुरू कीजिए।",
    trySample: "नमूना चैनल खोलें",
    previewOff: "इस चैनल का सार्वजनिक प्रीव्यू बंद है, इसलिए लिंक से नहीं पढ़ा जा सकता। टेलीग्राम डेस्कटॉप से चैट एक्सपोर्ट करके फ़ाइल खोलिए।",
    noCalls: "इन मैसेज में कोई कॉल पढ़ी नहीं जा सकी।",
    noCallsBody: (n: number, images: number) => `${n} मैसेज पढ़े गए। इनमें ${images} सिर्फ़ तस्वीरें हैं, जिन्हें यह संस्करण नहीं पढ़ सकता।`,
    failed: "हिसाब करते समय कुछ गड़बड़ हुई।",
    messages: "मैसेज",
    period: (a: string, b: string) => `${a} से ${b}`,

    account: "खाता",
    accountRule: (stake: string) => `हर कॉल में ${stake}, कम से कम एक लॉट`,
    ranOut: (date: string, n: number) => `${n} कॉल के बाद, ${date} से अगली कॉल के पैसे नहीं बचे`,
    afterCalls: (n: number) => `${n} कॉल के बाद`,
    band: "तीनों तरह से पढ़ने पर खाता इनके बीच ख़त्म होता है:",
    bandWorst: "और",
    bandWhy: "रोज़ के भाव यह नहीं बताते कि कोई भाव मैसेज से पहले आया या बाद में। मुख्य आँकड़ा संदिग्ध जीत तभी गिनता है जब चैनल ने उसी समय उसका एलान किया हो।",
    paperOnly: "यह काग़ज़ी हिसाब है: हर कॉल बताए गए भाव पर, हर बार बराबर रक़म, पहले टारगेट, स्टॉप-लॉस या एक्सपायरी तक। अगली कॉल के बारे में यह कुछ नहीं कहता।",

    record: "रिकॉर्ड",
    recordSub: (checked: number, calls: number) => `${calls} में से ${checked} कॉल एक्सचेंज के भाव पर चलाई जा सकीं`,
    classes: { target: "टारगेट तक पहुँची", stop: "स्टॉप-लॉस लगा", expired: "एक्सपायर हुई", worthless: "शून्य पर ख़त्म", horizon: "बिना किसी स्तर के बंद", open: "अभी खुली" },
    hitRate: "टारगेट तक पहुँची",
    byChance: "सिक्का उछालने पर",
    byChanceWhy: "अगर भाव बिना किसी दिशा के चलते, तो इन्हीं टारगेट और स्टॉप-लॉस वाली कॉल इतनी बार टारगेट छू लेतीं। इस आँकड़े के आसपास का हिट रेट कोई हुनर नहीं दिखाता।",
    flat: "हर कॉल में बराबर रक़म",
    flatSub: (n: number, stake: string) => `${stake} × ${n} कॉल, ख़र्च समेत`,
    meanReturn: "हर कॉल का औसत नतीजा",

    unchecked: "जिनकी जाँच नहीं हुई",
    codes: {
      "too-recent": "बहुत नई: भाव 30 दिन पीछे रखे जाते हैं",
      "before-data": "भाव के आँकड़ों से पुरानी",
      "off-exchange": "ऐसे एक्सचेंज पर, जो आँकड़ों में नहीं",
      "unknown-instrument": "शेयर या कॉन्ट्रैक्ट नहीं मिला",
      "not-traded": "उस दिन कॉन्ट्रैक्ट में सौदा नहीं हुआ",
      "price-mismatch": "बताया गया भाव उस दिन आया ही नहीं",
      "no-entry": "इंट्राडे कॉल, पर ख़रीद भाव नहीं",
      "level-not-reached": "ख़रीद का स्तर आया ही नहीं",
      "low-confidence": "ठीक से पढ़ी नहीं गई, छोड़ी गई",
      "no-funds": "खाते में पैसा नहीं बचा था",
    },
    unread: (n: number) => `${n} मैसेज कॉल जैसे थे, पर उनमें शेयर या कॉन्ट्रैक्ट का नाम पढ़ा नहीं जा सका`,
    images: (n: number) => `${n} मैसेज सिर्फ़ तस्वीरें हैं`,

    sections: { ledger: "बही", said: "बाद में क्या कहा", selling: "बिक्री", registration: "रजिस्ट्रेशन", pause: "ठहराव", method: "जाँच कैसे हुई" },
    pause: "अगली कॉल से पहले",

    ledger: "हर कॉल का हिसाब",
    filters: { all: "सब", target: "टारगेट", lost: "घाटा", doubtful: "पढ़ने पर निर्भर", unchecked: "जाँच नहीं हुई" },
    cols: { date: "तारीख़", call: "कॉल", inOut: "ख़रीद → निकास", result: "नतीजा", net: "नफ़ा/नुक़सान", balance: "खाता" },
    depends: "पढ़ने पर निर्भर",
    showMore: (n: number) => `${n} और दिखाएँ`,
    detail: {
      message: "मैसेज",
      checked: "जाँच कैसे हुई",
      contract: "किस पर चलाई गई",
      entered: "ख़रीद",
      exited: "निकास",
      basis: { stated: "बताए गए भाव पर", trigger: "जब ख़रीद का स्तर आया", open: "खुलने के भाव पर", close: "बंद भाव पर" },
      exitBasis: { target: "पहले टारगेट पर", stop: "स्टॉप-लॉस पर", "gap-open": "खुलते ही, स्तर के पार", close: "बंद भाव पर", "next-open": "अगले दिन खुलने पर", settlement: "एक्सपायरी की क़ीमत पर", "last-price": "आख़िरी सौदे के भाव पर" },
      other: "दूसरी तरह पढ़ने पर",
      best: "चैनल के लिए सबसे अच्छा",
      worst: "चैनल के लिए सबसे बुरा",
      lots: (lots: number, qty: number) => `${lots} लॉट (${qty} यूनिट)`,
      shares: (qty: number) => `${qty} शेयर`,
      costs: "ख़र्च",
      notes: "मैसेज से पढ़ा गया",
    },

    said: "चैनल ने बाद में क्या कहा",
    saidWinners: (a: number, b: number) => `${b} जीती हुई कॉल में से ${a} पर जीत का मैसेज आया`,
    saidLosers: (a: number, b: number) => `${b} हारी हुई कॉल में से सिर्फ़ ${a} का दोबारा ज़िक्र हुआ`,
    saidAdmitted: (a: number) => (a === 0 ? "एक भी मैसेज स्टॉप-लॉस या घाटा नहीं मानता" : `${a} मैसेज स्टॉप-लॉस या घाटा मानते हैं`),
    saidUnsupported: (n: number) => `${n} "टारगेट हिट" मैसेज, जबकि टारगेट का भाव आया ही नहीं था`,
    saidImpossible: (n: number) => `${n} मैसेज ऐसा भाव बताते हैं जिस पर कॉन्ट्रैक्ट कभी बिका ही नहीं`,
    saidClaim: (pct: number) => `चैनल का अपना दावा: ${pct}% सटीक`,
    claimed: "दावा",
    reached: "सबसे दूर जहाँ तक गया",

    selling: "मैसेज किस काम के हैं",
    sellingSub: (a: number, b: number) => `${b} में से ${a} मैसेज कुछ बेचते हैं`,
    cues: {
      "paid-group": "पेड या प्रीमियम ग्रुप",
      payment: "पेमेंट लिंक और UPI आईडी",
      contact: "\"मैसेज कीजिए\" और फ़ोन नंबर",
      "join-link": "दूसरे ग्रुप के लिंक",
      guarantee: "गारंटी और श्योर शॉट",
      "profit-brag": "मुनाफ़े के आँकड़े और स्क्रीनशॉट",
      urgency: "जल्दी कीजिए, सीमित सीटें",
      "account-handling": "आपका खाता चलाने की पेशकश",
      "paywalled-levels": "स्टॉप-लॉस या टारगेट पैसे देने पर",
    },

    registration: "SEBI रजिस्ट्रेशन",
    regNone: "चैनल कोई SEBI रजिस्ट्रेशन नंबर नहीं दिखाता। फ़ीस लेकर ख़रीद-बिक्री की कॉल देने के लिए रिसर्च एनालिस्ट या इन्वेस्टमेंट एडवाइज़र का रजिस्ट्रेशन ज़रूरी है।",
    regOn: (no: string, name: string) => `${no} SEBI के रजिस्टर में "${name}" के नाम पर है।`,
    regOnWarn: "नंबर असली होने से यह साबित नहीं होता कि चैनल उसी व्यक्ति का है: रजिस्टर्ड नामों की नक़ल अक्सर होती है। नाम को चैनल से मिलाइए।",
    regOff: (no: string) => `${no} SEBI के रजिस्टर में नहीं है।`,
    regAsOf: (date: string) => `रजिस्टर sebi.gov.in से ${date} को लिया गया`,
    routeUnreg: "बिना रजिस्ट्रेशन वाले चैनल की शिकायत: SEBI का मार्केट इंटेलिजेंस पोर्टल (mi.sebi.gov.in)। पैसा डूबा हो तो: cybercrime.gov.in या 1930 पर कॉल।",
    routeReg: "रजिस्टर्ड एनालिस्ट की शिकायत SCORES (scores.sebi.gov.in) पर होती है।",

    verdict: {
      tag: "सीधी भाषा में",
      headBehind: (start: string, end: string) => `${start} के ${end} रह गए।`,
      headAhead: "काग़ज़ पर फ़ायदा। यह पैसे देने की वजह नहीं है।",
      headNothing: "इन कॉल की जाँच अभी नहीं हो सकती।",
      stake: (stake: string) => `चैनल की हर कॉल में ${stake} लगाए गए।`,
      broke: (n: string) => `${n} कॉल के बाद अगली कॉल के लिए पैसे नहीं बचे।`,
      aheadFigure: (start: string, end: string) => `काग़ज़ पर ${start} के ${end} हो गए।`,
      paper: "यह आँकड़ा मानता है कि हर कॉल ठीक बताए गए भाव पर, मैसेज आते ही ली गई। असल में लोग देर से और महँगे भाव पर ख़रीद पाते हैं।",
      range: (lo: string, hi: string) => `दिन के भाव दूसरी तरह पढ़ें तो यही कॉल ${lo} और ${hi} के बीच ख़त्म होती हैं।`,
      hit: (hit: string, coin: string) => `टारगेट ${hit} बार लगा। उन्हीं टारगेट और स्टॉप-लॉस पर सिर्फ़ संयोग से ${coin} बार लग जाता।`,
      paywalled: (n: string, one: boolean) => (one ? "स्टॉप-लॉस पैसे देने पर ही बताया जाता था।" : `${n} कॉल में स्टॉप-लॉस पैसे देने पर ही बताया जाता था।`),
      noStop: (n: string, m: string) => `${m} में से ${n} कॉल में स्टॉप-लॉस नहीं था।`,
      admitted: (lost: string, n: string) => `${lost} कॉल में घाटा हुआ। घाटा मानने वाले मैसेज: ${n}।`,
      unsupported: (n: string) => `${n} मैसेज ऐसा भाव बताते हैं जिस पर कॉन्ट्रैक्ट उस समय तक बिका ही नहीं था।`,
      regNone: "चैनल कोई SEBI रजिस्ट्रेशन नंबर नहीं दिखाता।",
      regOn: "चैनल जो नंबर दिखाता है वह SEBI के रजिस्टर में है। यह ज़रूर देखिए कि चैनल सच में उसी नाम का है।",
      regOff: "चैनल जो रजिस्ट्रेशन नंबर दिखाता है वह SEBI के रजिस्टर में नहीं है।",
      selling: (a: string, b: string) => `${b} में से ${a} मैसेज कुछ बेचते हैं।`,
      promise: (words: string) => `मैसेज में ${words} लिखा है। बाज़ार में नतीजे का वादा कोई नहीं कर सकता।`,
      tooRecent: "भाव 30 दिन पीछे रखे जाते हैं, इसलिए पिछले एक महीने की कॉल की जाँच अभी नहीं हो सकती।",
      cannot: "इन कॉल को एक्सचेंज के भावों से मिलाया नहीं जा सका।",
      fno: "SEBI के अपने अध्ययन में इक्विटी फ़्यूचर और ऑप्शन के 10 में से 9 आम ट्रेडरों को घाटा हुआ।",
      next: "इनमें से कुछ भी यह नहीं बताता कि अगली कॉल का क्या होगा।",
      percent: "प्रतिशत",
      rupees: "रुपये",
      noReplay: "अभी किसी कॉल की जाँच नहीं हो सकी",
    },

    whatIf: {
      nav: "अगर",
      title: "वही कॉल, आपके पैसे के साथ",
      lead: "स्लाइडर खिसकाइए। वही कॉल, वही एक्सचेंज के भाव; बदलता है तो सिर्फ़ पैसा।",
      capital: "शुरुआत में आपके पास",
      stake: "हर कॉल में कितना हिस्सा",
      borrowed: "कितना हिस्सा उधार का",
      perCall: (amount: string) => `हर कॉल में ${amount}`,
      borrowedOf: (amount: string) => `इसमें ${amount} उधार के`,
      loanNote: (rate: number) => `उधार पर ${rate}% महीने का ब्याज लगाया गया है, जैसा झटपट लोन ऐप लेते हैं।`,
      ends: "खाते में अंत में बचे",
      ranOut: (date: string, n: number) => `${n} कॉल के बाद, ${date} से अगली कॉल के पैसे नहीं बचे`,
      taken: (n: number) => `${n} कॉल ली गईं`,
      fall: "ऊँचाई से सबसे बड़ी गिरावट",
      owed: "अंत में उधार देने वाले का बक़ाया",
      ownGone: (date: string) => `आपका अपना पैसा ${date} तक ख़त्म हो चुका था`,
      ownKept: "खाता कभी उधार की रक़म से नीचे नहीं गया",
      netWorth: "उधार चुकाने के बाद बचा",
      presets: { savings: "सिर्फ़ बचत", half: "आधा उधार", all: "हर कॉल में पूरा पैसा" },
    },

    flags: {
      nav: "पैटर्न",
      title: "कॉल के आसपास के पैटर्न",
      lead: "हर कॉल के आसपास भाव और वॉल्यूम की चाल, एक्सचेंज की अपनी फ़ाइलों से नापी गई। पैटर्न कोई नतीजा नहीं है: यह बताता है कि क्या हुआ, यह नहीं कि क्यों।",
      none: "इस चैनल की कॉल के आसपास इनमें से कोई पैटर्न नहीं मिला।",
      kinds: {
        "pump-shape": ["उछला, फिर गिर गया", "कॉल के दो दिन के भीतर भारी वॉल्यूम पर तेज़ उछाल, फिर दस दिन के भीतर ऊँचाई से काफ़ी नीचे।"],
        spike: ["भारी वॉल्यूम पर उछाल", "कॉल के दो दिन के भीतर सामान्य से कई गुना वॉल्यूम पर तेज़ उछाल।"],
        "pre-run": ["कॉल से पहले ही चढ़ चुका था", "कॉल से पहले के पाँच कारोबारी दिनों में भाव और वॉल्यूम पहले ही उछल चुके थे।"],
        "sme-board": ["SME प्लेटफ़ॉर्म के शेयर", "SME प्लेटफ़ॉर्म पर लिस्टेड, जहाँ थोड़ी-सी ख़रीद से भाव हिल जाता है।"],
        thin: ["कम कारोबार वाले शेयर", "इनमें सामान्य दिन पर बहुत कम पैसे का लेन-देन होता है।"],
        "expiry-day": ["एक्सपायरी के दिन ख़रीदे गए ऑप्शन", "कॉन्ट्रैक्ट के आख़िरी दिन ख़रीदे गए, जब ऑप्शन कुछ घंटों में पूरी क़ीमत खो सकता है।"],
      },
      calls: (n: number) => `${n} कॉल`,
      more: (n: number) => `और ${n}`,
    },

    complaint: {
      nav: "शिकायत",
      title: "इस चैनल की शिकायत",
      leadUnreg: "चैनल ऐसा कोई SEBI रजिस्ट्रेशन नहीं दिखाता जिसकी पुष्टि हो सके। बिना रजिस्ट्रेशन की सलाह की जानकारी SEBI के मार्केट इंटेलिजेंस पोर्टल पर दी जाती है। नीचे का मसौदा इसी रिपोर्ट से भरा गया है: पढ़िए, सुधारिए, और जो आपको पता है वह जोड़िए।",
      leadReg: "चैनल जो नंबर दिखाता है वह SEBI के रजिस्टर में है। अगर चैनल उसी एनालिस्ट का है तो शिकायत SCORES पर जाती है। अगर चैनल सिर्फ़ नंबर इस्तेमाल कर रहा है तो वह मार्केट इंटेलिजेंस पोर्टल का मामला है। नीचे का मसौदा इसी रिपोर्ट से भरा गया है।",
      draftNote: "मसौदा अंग्रेज़ी में है।",
      copy: "मसौदा कॉपी करें",
      copied: "कॉपी हो गया",
      csv: "कॉल की सूची डाउनलोड करें (CSV)",
      print: "सबूत की शीट छापें, या PDF में सहेजें",
      open: (site: string) => `${site} खोलें`,
      note: "यहाँ से कुछ नहीं भेजा जाता। शिकायत आप ख़ुद दर्ज करते हैं, अपने स्क्रीनशॉट के साथ।",
      sheet: "सबूत की शीट",
      generated: (date: string) => `${date} को चैनल के मैसेज और NSE व BSE की रोज़ की भाव फ़ाइलों से तैयार। जो नतीजे दिन के भीतर भावों के क्रम पर निर्भर हैं उन पर निशान लगा है। जिस मैसेज में एक्सपायरी नहीं लिखी, उसके लिए वह सबसे नज़दीकी एक्सपायरी ली गई जिसमें बताया गया ख़रीद भाव सच में आया था।`,
    },

    method: "जाँच कैसे हुई",
    methodPoints: [
      "भाव एक्सचेंज की अपनी रोज़ की फ़ाइलों से हैं (NSE और BSE भावकॉपी): उसी कॉन्ट्रैक्ट का खुला, ऊँचा, नीचा और बंद भाव।",
      "कॉल बताए गए भाव पर तभी ली जाती है जब वह भाव उस दिन आया हो। वह पहले टारगेट, स्टॉप-लॉस या एक्सपायरी पर ख़त्म होती है।",
      "रोज़ की फ़ाइल यह नहीं बताती कि कोई भाव मैसेज से पहले आया या बाद में। इसलिए हर कॉल तीन तरह से पढ़ी जाती है, और जो नतीजे पढ़ने पर निर्भर हैं उन पर निशान लगा है।",
      "भाव आज से 30 दिन पीछे रखे जाते हैं, जैसा SEBI निवेशक शिक्षा में बाज़ार भाव इस्तेमाल करने वाले टूल से चाहता है।",
    ],
    methodMore: "पूरे नियम",
  },

  method: {
    title: "कॉल की जाँच कैसे होती है",
    lead: "बही जो भी नियम लगाती है, उसी क्रम में। यहाँ कोई राय नहीं है: यह एक्सचेंज के अपने भावों पर सीधा हिसाब है।",
    rulesTitle: "नियम",
    rules: [
      ["मैसेज पढ़ना", "मैसेज तभी कॉल गिना जाता है जब उसमें शेयर या कॉन्ट्रैक्ट और कम से कम एक भाव पढ़ा जा सके। पढ़ने का काम तय नियमों से होता है, किसी भाषा मॉडल से नहीं, इसलिए एक ही मैसेज हर बार एक ही तरह पढ़ा जाता है। जो मैसेज पढ़े नहीं जा सके, वे गिनकर दिखाए जाते हैं, अंदाज़ा नहीं लगाया जाता।"],
      ["कॉन्ट्रैक्ट ढूँढना", "ऑप्शन को उसके ठीक स्ट्राइक, प्रकार और एक्सपायरी से मिलाया जाता है। मैसेज में एक्सपायरी न हो तो कॉल की तारीख़ के बाद की सबसे नज़दीकी एक्सपायरी ली जाती है; बताया गया भाव उस दिन उस कॉन्ट्रैक्ट के भावों से मेल न खाए तो अगली मेल खाने वाली एक्सपायरी ली जाती है।"],
      ["ख़रीद", "कॉल मैसेज में बताए गए भाव पर ली जाती है, पर तभी जब वह भाव उस दिन आया हो। \"250 के ऊपर ख़रीदें\" तब शुरू होती है जब 250 का भाव आए। बताया गया भाव दिन के दायरे से बाहर हो तो कॉल की जाँच नहीं हो सकती।"],
      ["निकास", "कॉल पहले टारगेट या स्टॉप-लॉस पर ख़त्म होती है, जो भाव पहले आए। दोनों न हों तो ऑप्शन एक्सपायरी तक रखा जाता है और इंडेक्स या शेयर के बंद भाव के हिसाब से निपटता है; शेयर दस कारोबारी दिन बाद बंद किया जाता है।"],
      ["पैसा", "शुरुआत ₹50,000 से। हर कॉल में ₹10,000: ऑप्शन और फ़्यूचर में पूरे लॉट, कम से कम एक। ब्रोकरेज, STT और एक्सचेंज शुल्क एक सीधे, बताए गए हिसाब से काटे जाते हैं। जब खाते में एक लॉट के पैसे न बचें, कॉल नहीं ली जाती।"],
    ],
    readingsTitle: "एक ही दिन, तीन तरह से पढ़ा गया",
    readingsBody: "एक्सचेंज की रोज़ की फ़ाइल दिन का खुला, ऊँचा, नीचा और बंद भाव देती है, यह नहीं कि वे किस क्रम में आए। जिस दिन कॉल आती है, उस दिन का ऊँचा भाव मैसेज से पहले का भी हो सकता है। इसलिए हर कॉल तीन तरह से चलाई जाती है।",
    readings: [
      ["सबसे अच्छा", "हर संदिग्ध भाव चैनल के पक्ष में पढ़ा जाता है। कोई भी एक कॉल इससे बेहतर नहीं हो सकती थी।"],
      ["सबसे बुरा", "भाव तभी गिना जाता है जब वह ख़रीद के बाद ही आया हो: दिन उसके पार बंद हुआ, या मैसेज बाज़ार खुलते ही आया और भाव खुलने के भाव और बताए गए भाव के बाहर है।"],
      ["मुख्य आँकड़ा", "संदिग्ध जीत तब गिनी जाती है जब चैनल ने उसी समय उसका एलान किया और उस दिन के भाव उसे ग़लत नहीं ठहराते। संदिग्ध स्टॉप-लॉस तब गिना जाता है जब चैनल चुप रहा।"],
    ],
    chanceTitle: "सिक्के का हिट रेट",
    chanceBody: "25% दूर का टारगेट और कोई स्टॉप-लॉस नहीं: बिना दिशा के चलने वाला भाव भी इसे पाँच में से लगभग चार बार छू लेता है, क्योंकि चूकने का एक ही रास्ता है, पहले शून्य तक गिरना। बही यही हिसाब चैनल की अपनी कॉल पर लगाती है: हर कॉल के लिए (ख़रीद − स्टॉप) ÷ (टारगेट − स्टॉप), स्टॉप न हो तो शून्य। इस आँकड़े के आसपास का हिट रेट कोई हुनर नहीं दिखाता। तब असली सवाल यह है कि चूकी हुई कॉल कितने में पड़ीं।",
    dataTitle: "आँकड़े कहाँ से आते हैं",
    data: [
      ["शेयर के भाव", "NSE कैश मार्केट की भावकॉपी, 1 जनवरी 2024 से हर कारोबारी दिन।"],
      ["ऑप्शन और फ़्यूचर", "NSE F&O भावकॉपी, और SENSEX व BANKEX के लिए BSE डेरिवेटिव भावकॉपी।"],
      ["स्प्लिट और बोनस", "लागू होने के दिन भाव के अंतर से पहचाने जाते हैं; बाद के भाव कॉल के समय के पैमाने पर लाए जाते हैं।"],
      ["SEBI रजिस्ट्रेशन", "SEBI के रिसर्च एनालिस्ट और इन्वेस्टमेंट एडवाइज़र के सार्वजनिक रजिस्टर की तारीख़ वाली प्रति।"],
      ["30 दिन का अंतर", "भाव उस दिन से 30 दिन पहले तक के हैं जिस दिन आँकड़े बनाए गए। SEBI निवेशक शिक्षा में बाज़ार भाव इसी अंतर के साथ इस्तेमाल करने देता है, इसलिए सबसे नई कॉल \"बहुत नई\" दिखती हैं।"],
    ],
    limitsTitle: "यह क्या नहीं कर सकता",
    limits: [
      "यह कारोबारी दिन के भीतर नहीं देख सकता। जो नतीजे दिन के भीतर भावों के क्रम पर निर्भर हैं उन पर निशान लगा है, और खाता एक दायरे में बताया जाता है।",
      "तस्वीर के रूप में डाली गई कॉल यह नहीं पढ़ सकता।",
      "कमोडिटी, करेंसी, क्रिप्टो या विदेशी बाज़ार के भाव इसके पास नहीं हैं, और ऐसी हर कॉल पर यह बात लिखी जाती है।",
      "जिस चैनल का सार्वजनिक प्रीव्यू बंद है, उसे यह सिर्फ़ एक्सपोर्ट फ़ाइल से पढ़ सकता है।",
      "स्प्लिट या बोनस के आर-पार स्टॉक ऑप्शन के कॉन्ट्रैक्ट नहीं बदले जाते।",
      "यह नहीं बता सकता कि मानने वाला सच में बताए गए भाव पर ख़रीद पाया या नहीं, या उसने मैसेज कितनी देर से देखा।",
      "हर कॉल के नतीजे की वजह सिर्फ़ अंग्रेज़ी में लिखी जाती है।",
      "कोई शेयर या कॉन्ट्रैक्ट आगे क्या करेगा, इस बारे में यह कुछ नहीं कहता, और कभी नहीं कहेगा।",
    ],
  },
  landing: {
    rail: ["बही", "एक कॉल", "सिक्के की कसौटी", "चैट", "तीन तरह से", "ठहराव", "शिकायत कहाँ"],
    scroll: "सबूत, एक-एक करके",

    oneCall: {
      tag: "प्रमाण ख · एक कॉल",
      title: "मैसेज में क्या लिखा था। एक्सचेंज में क्या दर्ज हुआ।",
      step1: (date: string, time: string) => `${date} · ${time} · मैसेज`,
      note1: "मैसेज में स्टॉप-लॉस नहीं है। वह अलग से बिकता है।",
      step2: "वही कॉन्ट्रैक्ट, दिन-ब-दिन",
      target: "टारगेट",
      bought: "ख़रीद",
      expiry: "एक्सपायरी",
      before: "कॉल से पहले",
      step3: (date: string) => `${date} · हिसाब`,
      note3: (entry: string, target: string) => `${entry} पर ख़रीदा। ${target} कभी नहीं आया। शून्य पर ख़त्म।`,
      sum: (qty: number, entry: string, costs: string) => `${qty} यूनिट × ₹${entry}, और ${costs} ख़र्च`,
    },

    coin: {
      tag: "प्रमाण ग · सिक्के की कसौटी",
      title: "क्या सिक्का इससे अच्छा करता?",
      lead: "बिना स्टॉप-लॉस का टारगेट सिर्फ़ संयोग से भी चार में से लगभग तीन बार लग जाता है। हिट रेट का मतलब तभी है जब उसे इस आँकड़े के बग़ल में रखा जाए कि उन्हीं टारगेट और स्टॉप-लॉस पर सिक्का कितनी बार जीतता।",
      result: (below: number, total: number) => `${total} असली चैनलों में से ${below} का टारगेट सिक्के से भी कम बार लगा।`,
      resultBest: (n: number) => `${n} तब भी सिक्के से नीचे रहते हैं जब हर संदिग्ध नतीजा चैनल के पक्ष में पढ़ा जाए।`,
      xAxis: "उन्हीं टारगेट और स्टॉप-लॉस पर सिक्का कितनी बार जीतता →",
      yAxis: "चैनल कितनी बार जीता →",
      diagonal: "सिक्के के बराबर",
      above: "प्रमाण क",
      whisker: "बिंदु: मुख्य आँकड़ा · रेखा: सबसे बुरे से सबसे अच्छे तक",
      foot: (read: number, total: number, min: number) => `${read} सार्वजनिक चैनल पढ़े गए। जिन ${total} में टारगेट वाली ${min} या ज़्यादा कॉल चलाई जा सकीं, वे दिखाए गए हैं। नाम छिपाए गए हैं।`,
      caveat: "सिक्के से आगे निकलना और पैसा बनाना एक बात नहीं है। वह इससे तय होता है कि चूकी हुई कॉल कितने में पड़ीं।",
    },

    chat: {
      tag: "प्रमाण घ · चैट",
      title: (n: string) => `${n} मैसेज। घाटे का एक भी नहीं।`,
      lead: "उसी चैनल का हर मैसेज, उसी क्रम में। हर मैसेज एक ख़ाना।",
      kinds: { call: "कॉल", profit: "पॉइंट और मुनाफ़े के मैसेज", selling: "बिक्री के मैसेज", loss: "घाटे के मैसेज", other: "बाक़ी सब" },
      won: (a: number, b: number) => `${b} जीती हुई कॉल में से ${a} के बाद मुनाफ़े का मैसेज आया`,
      lost: (a: number, b: number) => `${b} कॉल में घाटा हुआ। यह मानने वाले मैसेज: ${a}`,
      stop: (a: number, b: number) => `${b} में से ${a} कॉल में स्टॉप-लॉस नहीं था। मैसेज में लिखा था "SL PAID"`,
    },

    readings: {
      tag: "प्रमाण ङ · जो रोज़ का भाव तय नहीं कर सकता",
      title: "एक दिन। तीन ईमानदार हिसाब।",
      lead: (date: string, time: string, contract: string, target: string) => `${date}, ${time}। चैनल ${contract} की कॉल देता है, टारगेट ${target}। एक्सचेंज की उस दिन की फ़ाइल में सबसे ऊँचा भाव ठीक ${target} है।`,
      question: (time: string) => `${time} से पहले, या बाद में? रोज़ की फ़ाइल यह नहीं बताती।`,
      bar: "दिन का भाव",
      ohlc: { o: "खुला", h: "ऊँचा", l: "नीचा", c: "बंद" },
      message: "मैसेज",
      pathA: "ऊँचा भाव मैसेज से पहले आया",
      pathB: "ऊँचा भाव मैसेज के बाद आया",
      illustration: "दो अलग दिन, जिनका रोज़ का भाव एक जैसा दिखता है। रास्ते समझाने के लिए बनाए गए हैं; भाव एक्सचेंज का है।",
      rows: {
        best: ["चैनल के लिए सबसे अच्छा", "हर संदिग्ध भाव को पहुँचा हुआ गिना जाता है।"],
        worst: ["चैनल के लिए सबसे बुरा", "भाव तभी गिना जाता है जब वह कॉल के बाद ही आया हो।"],
        likely: ["मुख्य आँकड़ा", "संदिग्ध जीत तभी गिनी जाती है जब चैनल ने उसी समय उसका एलान किया हो।"],
      },
      quoted: (q: string) => `उस सुबह चैनल के अपने अपडेट ${q} पर रुक गए थे।`,
      close: "ऐसे हर नतीजे पर बही में निशान लगता है, और खाता एक दायरे में बताया जाता है।",
    },

    pause: {
      tag: "प्रमाण च · अगली कॉल से पहले",
      title: "मैसेज और पैसे के बीच चौबीस घंटे।",
      lead: "टिप के साथ एक घड़ी आती है: अभी, जल्दी, सीमित सीटें। ठहराव कार्ड उसके बग़ल में एक धीमी घड़ी रख देता है।",
      lookFor: "मैसेज में ये तीन बातें देखिए",
      questions: ["स्टॉप-लॉस मैसेज में है, या अलग से बिकता है?", "भेजने वाला SEBI के रजिस्टर में है?", "पिछली दस कॉल का क्या हुआ?"],
      card: "ठहराव कार्ड",
      record: "चैनल का रिकॉर्ड",
      hit: (a: string, b: string) => `टारगेट ${a} बार लगा। सिक्का: ${b}।`,
      admitted: (lost: number, n: number) => `${lost} कॉल में घाटा हुआ। यह मानने वाले मैसेज: ${n}।`,
      noStop: "स्टॉप-लॉस अलग से बिकता है।",
      reasonLabel: "आप यह कॉल क्यों लेना चाहते हैं?",
      placeholder: "अपने शब्दों में लिखिए",
      start: "24 घंटे शुरू करें",
      running: "अपनी वजह दोबारा पढ़िए, इतने समय बाद",
      done: "24 घंटे बीत गए। अपनी वजह दोबारा पढ़िए।",
      reset: "मिटाएँ",
      saved: "सिर्फ़ इसी फ़ोन में रहता है। कहीं भेजा नहीं जाता।",
    },

    where: {
      tag: "प्रमाण छ · शिकायत कहाँ करें",
      title: "बिना रजिस्ट्रेशन की सलाह की शिकायत की एक जगह है।",
      lead: "फ़ीस लेकर ख़रीद-बिक्री की कॉल देने के लिए SEBI का रजिस्ट्रेशन ज़रूरी है। चैनल जो नंबर दिखाता है उसे जाँचिए, फिर सही रास्ता चुनिए।",
      checkLabel: "रजिस्ट्रेशन नंबर जाँचिए",
      placeholder: "INH… या INA… नंबर",
      check: "जाँचें",
      bad: "रजिस्ट्रेशन नंबर INH000001234 या INA000001234 जैसा होता है।",
      found: (no: string, name: string, from: string) => `${no} SEBI के रजिस्टर में "${name}" के नाम पर है, ${from} से।`,
      notFound: (no: string) => `${no} SEBI के रजिस्टर में नहीं है।`,
      asOf: (date: string) => `रजिस्टर sebi.gov.in से ${date} को लिया गया`,
      loading: "रजिस्टर खुल रहा है",
      routes: [
        ["चैनल रजिस्टर्ड नहीं है", "SEBI का मार्केट इंटेलिजेंस पोर्टल", "mi.sebi.gov.in", "https://mi.sebi.gov.in/"],
        ["पैसा डूब चुका है", "नेशनल साइबर क्राइम पोर्टल, या 1930 पर कॉल", "cybercrime.gov.in", "https://cybercrime.gov.in/"],
        ["रजिस्टर्ड एनालिस्ट या एडवाइज़र", "SEBI SCORES", "scores.sebi.gov.in", "https://scores.sebi.gov.in/"],
      ] as [string, string, string, string][],
      if: "अगर",
    },


    closing: {
      title: "वह चैनल लाइए जिसे आप पैसे देने वाले हैं।",
      foot: "Reckoning सिर्फ़ बीता हुआ देखता है। कोई शेयर या कॉन्ट्रैक्ट आगे क्या करेगा, इस बारे में यह कुछ नहीं कहता।",
      sources: "भाव: NSE और BSE की रोज़ की भावकॉपी। रजिस्टर: sebi.gov.in।",
    },
  },
  caseFile: {
    nav: "SEBI का एक मामला",
    tag: "केस फ़ाइल",
    title: "वही जाँच, उस मामले पर जिसे SEBI पहले ही देख चुका है।",
    lead: (date: string) => `${date} को SEBI ने सोशल मीडिया पर डाली गई शेयर सिफ़ारिशों के बारे में एक अंतरिम आदेश दिया। आदेश के परिशिष्ट A में वे सिफ़ारिशें दर्ज हैं जिनके आधार पर रक़म ज़ब्त की गई। हमने इस साइट की पैटर्न जाँच उन्हीं तारीख़ों पर चलाई, और उन्हीं शेयरों के आम दिनों पर भी।`,
    caution: "एकतरफ़ा अंतरिम आदेश वह दर्ज करता है जो SEBI को पहली नज़र में मिला। यह किसी के ख़िलाफ़ अंतिम फ़ैसला नहीं है, और इस पन्ने पर किसी व्यक्ति का नाम नहीं है।",
    orderRef: "आदेश",
    impounded: "आदेश से ज़ब्त रक़म",
    recos: "परिशिष्ट A में सिफ़ारिशें",
    measured: "हमारी भाव फ़ाइलों के भीतर",
    coverage: (measured: number, total: number, stocks: number, from: string) => `${total} में से ${measured} सिफ़ारिशें, ${stocks} शेयरों में, हमारी भाव फ़ाइलों के भीतर आती हैं (NSE, ${from} से)। बाक़ी ऐसे शेयरों में हैं जो सिर्फ़ BSE पर चलते हैं, या आँकड़ों से पुरानी हैं।`,
    ratesTitle: "हर पैटर्न कितनी बार दिखा",
    onRecos: "आदेश की सिफ़ारिशों के बाद",
    onOrdinary: "उन्हीं शेयरों के आम दिनों पर",
    patterns: {
      spike: ["भारी वॉल्यूम पर उछाल", "दो कारोबारी दिन के भीतर 8% या ज़्यादा ऊपर, सामान्य से तीन गुना या ज़्यादा वॉल्यूम पर।"],
      pump: ["उछला, फिर गिर गया", "वही उछाल, और फिर दस कारोबारी दिन के भीतर ऊँचाई से 15% या ज़्यादा की गिरावट।"],
      preRun: ["पोस्ट से पहले ही चढ़ चुका था", "पहले के पाँच कारोबारी दिनों में 10% या ज़्यादा ऊपर, सामान्य से तीन गुना या ज़्यादा वॉल्यूम पर।"],
      thin: ["कम कारोबार वाला", "सामान्य दिन पर ₹25 लाख से कम का लेन-देन।"],
    },
    times: (x: string) => `${x} गुना ज़्यादा बार`,
    notMore: "आम दिनों से ज़्यादा नहीं। इस जाँच ने इन शेयरों को अलग नहीं पहचाना।",
    smeLine: (n: number, total: number) => `नापी गई ${total} सिफ़ारिशों में से ${n} SME प्लेटफ़ॉर्म के शेयरों में थीं।`,
    chartsTitle: "इनमें से तीन शेयर",
    chartsLead: "बंद भाव और वॉल्यूम। हर लाल रेखा आदेश में दर्ज एक सिफ़ारिश है।",
    recoCount: (n: number) => `${n} सिफ़ारिशें`,
    tableTitle: "नापी गई हर सिफ़ारिश",
    cols: { day: "पहला कारोबारी दिन", stock: "शेयर", up: "2 दिन में चढ़ा", volume: "वॉल्यूम", fall: "फिर गिरा", marks: "पैटर्न" },
    sme: "SME",
    showAll: (n: number) => `सभी ${n} दिखाएँ`,
    source: "स्रोत: SEBI का आदेश, परिशिष्ट A, पृष्ठ 198 से 234। भाव: NSE की रोज़ की भावकॉपी।",
    openOrder: "sebi.gov.in पर आदेश खोलें",
  },
};
