// Every word the interface shows, in English. The other languages mirror this file key for key. Nothing here tells anyone what to do with a stock:
// the product looks backward only.

export const en = {
  nav: { reckon: "Reckon a channel", method: "How it is checked", language: "Language" },
  status: { prices: "Prices", to: "to", lag: "30-day lag" },

  hero: {
    eyebrow: "The record a tip channel never posts",
    // [text, set in red italics]
    title: [
      ["Every tip channel has a day of ", false],
      ["reckoning.", true],
    ] as [string, boolean][],
    lead: "Yours comes before you pay for it.",
    placeholder: "channel name or link",
    go: "Reckon it",
    or: "or bring",
    sources: { export: "Telegram export", whatsapp: "WhatsApp chat", shots: "Screenshots", paste: "Paste messages" },
    promise: ["No account", "Chats stay on your device", "Looks at the past only"],
    badLink: "That does not look like a public channel link. Try t.me/channelname.",
  },

  replay: {
    sample: "A real public channel · name withheld",
    sampleTitle: "An index-options channel",
    subscribers: "subscribers",
    reading: "reading",
    ledger: "Ledger",
    rule: "₹10,000 in every call · one lot minimum · first target or expiry",
    balance: "Account",
    cols: { date: "Date", contract: "Contract", in: "In", out: "Out", result: "Result", net: "Net" },
    stamps: { target: "Target", expired: "Expired", zero: "Expired at zero", stop: "Stop-loss", horizon: "Closed", open: "Open", unverifiable: "Could not check", "no-funds": "No money left", "not-triggered": "Never triggered" },
    lots: "lot",
    verdictA: "could not pay for the next call",
    verdictDays: (n: number) => `${n} days`,
    summary: (taken: number, zero: number, brags: number, losses: number) =>
      `${taken} calls taken. ${zero} expired at zero. In the same week the channel posted ${brags} profit messages and ${losses === 0 ? "not one about a loss" : `${losses} about a loss`}.`,
    slPaid: "The stop-loss was behind a paywall.",
    full: "Open the full reckoning",
    again: "Replay",
    peak: "peak",
    source: (to: string) => `Exchange prices: NSE and BSE daily bhavcopy to ${to}. Costs included.`,
    exhibit: "Exhibit A · the ledger",
    exhibitSub: (subs: string) => `A real channel, ${subs} subscribers. ₹10,000 in every call.`,
    inDays: (n: number) => `in ${n} days`,
    dependsShort: "Depends on reading",
    range: (n: number, lo: string, hi: string) => `${n} of these results depend on how the day's prices are read. Across the three readings the week ends between ${lo} and ${hi}.`,
    listen: "Listen",
    stopListening: "Stop",
    // every figure arrives already written out in words (see lib/say.ts)
    spoken: (n: { subs: string; start: string; stake: string; end: string; days: string; taken: string; zero: string; brags: string }) =>
      `A real tip channel, with ${n.subs} subscribers. ${n.start} rupees, put ${n.stake} at a time into every call it posted, became ${n.end} rupees in ${n.days} days. ${n.taken} calls were taken. ${n.zero} expired at zero. In the same week, the channel posted ${n.brags} messages about profit, and not one about a loss. The stop-loss was behind a paywall.`,
  },

  report: {
    stages: { messages: "Reading the channel", prices: "Fetching exchange prices", replaying: "Replaying calls" },
    readSoFar: (n: number, back: string) => `${n.toLocaleString("en-IN")} messages read, back to ${back}`,
    replayed: (a: number, b: number) => `${a} of ${b} calls replayed`,
    noSource: "Bring a channel to reckon",
    noSourceBody: "Paste a public Telegram channel, open an export, or start with the sample below.",
    trySample: "Open the sample channel",
    previewOff: "This channel has its public preview switched off, so it cannot be read from a link. Export the chat from Telegram Desktop and open the file instead.",
    noCalls: "No calls could be read in these messages.",
    noCallsBody: (n: number, images: number) => `${n} messages were read. ${images} of them are pictures with no text, which this build cannot read.`,
    failed: "Something went wrong while reckoning.",
    messages: "messages",
    period: (a: string, b: string) => `${a} to ${b}`,

    account: "The account",
    accountRule: (stake: string) => `${stake} in every call, one lot minimum`,
    ranOut: (date: string, n: number) => `Could not pay for a call from ${date}, after ${n} calls`,
    afterCalls: (n: number) => `after ${n} calls`,
    band: "Across the three readings it ends between",
    bandWorst: "and",
    bandWhy: "Daily prices cannot show whether a price was touched before or after a message. The main figure counts a doubtful win only when the channel announced it at the time.",
    paperOnly: "A paper record: every call taken at the quoted price, the same stake each time, held to its first target, stop-loss or expiry. It says nothing about the next call.",

    record: "The record",
    recordSub: (checked: number, calls: number) => `${checked} of ${calls} calls could be replayed on exchange prices`,
    classes: { target: "Reached target", stop: "Stop-loss hit", expired: "Expired", worthless: "Expired at zero", horizon: "Closed, no level hit", open: "Still open" },
    hitRate: "Reached target",
    byChance: "A coin would manage",
    byChanceWhy: "If prices moved with no direction at all, calls with these targets and stop-losses would reach target this often. A hit rate near this number shows no skill.",
    flat: "Same stake in every replayed call",
    flatSub: (n: number, stake: string) => `${stake} × ${n} calls, costs included`,
    meanReturn: "Average result per call",

    unchecked: "Not checked",
    codes: {
      "too-recent": "Too recent: price data is kept 30 days behind",
      "before-data": "Older than the price data",
      "off-exchange": "Trades on an exchange outside the data",
      "unknown-instrument": "Stock or contract not found",
      "not-traded": "Contract did not trade that day",
      "price-mismatch": "Quoted price never traded that day",
      "no-entry": "Intraday call with no entry price",
      "level-not-reached": "Entry level never reached",
      "low-confidence": "Read with low confidence, left out",
      "no-funds": "Account had no money left",
    },
    unread: (n: number) => `${n} messages looked like calls but named no stock or contract that could be read`,
    images: (n: number) => `${n} messages are pictures with no text`,

    sections: { ledger: "Ledger", said: "What it said afterwards", selling: "Selling", registration: "Registration", pause: "Pause", method: "How this was checked" },
    pause: "Before the next call",

    ledger: "Every call, settled",
    filters: { all: "All", target: "Target", lost: "Lost", doubtful: "Depends on reading", unchecked: "Not checked" },
    cols: { date: "Date", call: "Call", inOut: "In → out", result: "Result", net: "Net", balance: "Account" },
    depends: "depends on reading",
    showMore: (n: number) => `Show ${n} more`,
    detail: {
      message: "The message",
      checked: "How it was checked",
      contract: "Replayed on",
      entered: "Entered",
      exited: "Exited",
      basis: { stated: "at the quoted price", trigger: "when the entry level traded", open: "at the opening price", close: "at the closing price" },
      exitBasis: { target: "at the first target", stop: "at the stop-loss", "gap-open": "at the open, past the level", close: "at the close", "next-open": "at the next open", settlement: "at expiry value", "last-price": "at the last traded price" },
      other: "Other readings",
      best: "Best for the channel",
      worst: "Worst for the channel",
      lots: (lots: number, qty: number) => `${lots} lot${lots > 1 ? "s" : ""} (${qty} units)`,
      shares: (qty: number) => `${qty} shares`,
      costs: "costs",
      notes: "Read from the message",
    },

    said: "What the channel said afterwards",
    saidWinners: (a: number, b: number) => `${a} of ${b} winning calls got a victory post`,
    saidLosers: (a: number, b: number) => `${a} of ${b} losing calls were ever mentioned again`,
    saidAdmitted: (a: number) => (a === 0 ? "Not one post admits a stop-loss or a loss" : `${a} posts admit a stop-loss or a loss`),
    saidUnsupported: (n: number) => `${n} "target hit" posts where the target price had not traded`,
    saidImpossible: (n: number) => `${n} posts quote a price the contract never traded at`,
    saidClaim: (pct: number) => `The channel's own claim: ${pct}% accuracy`,
    claimed: "claimed",
    reached: "furthest it traded",

    selling: "What the messages are for",
    sellingSub: (a: number, b: number) => `${a} of ${b} messages sell something`,
    cues: {
      "paid-group": "Paid or premium group",
      payment: "Payment links and UPI ids",
      contact: "\"Message me\" and phone numbers",
      "join-link": "Links into other groups",
      guarantee: "Guarantees and sure shots",
      "profit-brag": "Profit figures and screenshots",
      urgency: "Hurry, limited seats",
      "account-handling": "Offers to trade your account",
      "paywalled-levels": "Stop-loss or target held back for payment",
    },

    registration: "SEBI registration",
    regNone: "The channel shows no SEBI registration number. Giving buy and sell calls for a fee requires registration as a Research Analyst or Investment Adviser.",
    regOn: (no: string, name: string) => `${no} is on SEBI's register as "${name}".`,
    regOnWarn: "A real number does not prove the channel belongs to that person: registered names are often impersonated. Check the name against the channel.",
    regOff: (no: string) => `${no} is not on SEBI's register.`,
    regAsOf: (date: string) => `Register copied from sebi.gov.in on ${date}`,
    routeUnreg: "To report an unregistered channel: SEBI's Market Intelligence portal (mi.sebi.gov.in). If money was lost: cybercrime.gov.in or call 1930.",
    routeReg: "A complaint against a registered analyst goes to SCORES (scores.sebi.gov.in).",

    verdict: {
      tag: "In plain words",
      headBehind: (start: string, end: string) => `${start} became ${end}.`,
      headAhead: "Ahead on paper. That is not a reason to pay.",
      headNothing: "Too soon to replay these calls.",
      stake: (stake: string) => `${stake} went into every call the channel posted.`,
      broke: (n: string) => `After ${n} calls there was not enough left to take the next one.`,
      aheadFigure: (start: string, end: string) => `On paper, ${start} became ${end}.`,
      paper: "That figure takes every call at the quoted price, the moment it was posted. A follower gets in later, at a worse price.",
      range: (lo: string, hi: string) => `Read the day's prices another way and the same calls end between ${lo} and ${hi}.`,
      hit: (hit: string, coin: string) => `Targets were reached ${hit} of the time. Chance alone, with the same targets and stop-losses, would reach ${coin}.`,
      paywalled: (n: string, one: boolean) => (one ? "The stop-loss was held back for payment." : `In ${n} calls the stop-loss was held back for payment.`),
      noStop: (n: string, m: string) => `${n} of ${m} calls gave no stop-loss.`,
      admitted: (lost: string, n: string) => `${lost} calls lost money. Posts that admit a loss: ${n}.`,
      unsupported: (n: string) => `${n} result posts quote a price the contract had not traded at.`,
      regNone: "The channel shows no SEBI registration number.",
      regOn: "It shows a number that is on SEBI's register. Check that the channel really belongs to that name.",
      regOff: "It shows a registration number that is not on SEBI's register.",
      selling: (a: string, b: string) => `${a} of ${b} messages sell something.`,
      promise: (words: string) => `The messages say ${words}. No one can promise a result in the market.`,
      tooRecent: "Price data is kept 30 days behind, so calls from the last month cannot be replayed yet.",
      cannot: "These calls could not be matched to exchange prices.",
      fno: "SEBI's own study found that 9 in 10 individual traders in equity futures and options lost money.",
      next: "None of this says what the next call will do.",
      percent: "percent",
      rupees: "rupees",
      noReplay: "No call could be replayed yet",
    },

    whatIf: {
      nav: "What if",
      title: "The same calls, with your money",
      lead: "Move the sliders. The same calls replay on the same exchange prices; only the money changes.",
      capital: "Money you start with",
      stake: "Share put into each call",
      borrowed: "Share that is borrowed",
      perCall: (amount: string) => `${amount} in every call`,
      borrowedOf: (amount: string) => `${amount} of it borrowed`,
      loanNote: (rate: number) => `Borrowed money is charged ${rate}% a month, the range of an instant app loan.`,
      ends: "The account ends at",
      ranOut: (date: string, n: number) => `Could not pay for a call from ${date}, after ${n} calls`,
      taken: (n: number) => `${n} calls taken`,
      fall: "Deepest fall from a peak",
      owed: "Owed to the lender at the end",
      ownGone: (date: string) => `Your own money was gone by ${date}`,
      ownKept: "The balance never fell below what was borrowed",
      netWorth: "Left after repaying the loan",
      presets: { savings: "Savings only", half: "Half borrowed", all: "Everything in each call" },
    },

    flags: {
      nav: "Patterns",
      title: "Patterns around the calls",
      lead: "Shapes in price and volume around each call, measured on the exchange's own files. A pattern is not a finding: it shows what happened, not why.",
      none: "None of these patterns appear around this channel's calls.",
      kinds: {
        "pump-shape": ["Jumped, then fell back", "Up sharply on heavy volume within two days of the call, then well down from the peak within ten."],
        spike: ["Jumped on heavy volume", "Up sharply on several times the normal volume within two days of the call."],
        "pre-run": ["Already running before the call", "Price and volume had jumped in the five trading days before the call."],
        "sme-board": ["SME-platform stocks", "Listed on the SME platform, where a small amount of buying moves the price."],
        thin: ["Thinly traded stocks", "Very little money changes hands in these on a normal day."],
        "expiry-day": ["Options bought on expiry day", "Bought on the contract's last day, when an option can lose its whole value within hours."],
      },
      calls: (n: number) => `${n} call${n === 1 ? "" : "s"}`,
      more: (n: number) => `and ${n} more`,
    },

    complaint: {
      nav: "Report it",
      title: "Report this channel",
      leadUnreg: "The channel shows no SEBI registration that could be confirmed. Information about unregistered advice goes to SEBI's Market Intelligence portal. The draft below is filled in from this report: read it, correct it, add what you know.",
      leadReg: "The channel shows a number that is on SEBI's register. If it is run by that analyst, a complaint goes to SCORES. If it only uses the number, that is for the Market Intelligence portal. The draft below is filled in from this report.",
      draftNote: "The draft is in English.",
      copy: "Copy the draft",
      copied: "Copied",
      csv: "Download the call list (CSV)",
      print: "Print the evidence sheet, or save it as PDF",
      open: (site: string) => `Open ${site}`,
      note: "Nothing is sent from here. You file it yourself, with your own screenshots.",
      sheet: "Evidence sheet",
      generated: (date: string) => `Prepared on ${date} from the channel's messages and the NSE and BSE daily price files. Results that depend on the order of prices within a day are marked. Where a message names no expiry, the nearest expiry in which the quoted entry price traded was used.`,
    },

    method: "How this was checked",
    methodPoints: [
      "Prices are the exchanges' own daily files (NSE and BSE bhavcopy): open, high, low and close of the exact contract.",
      "A call is entered at its quoted price only if that price traded that day. It ends at the first target, the stop-loss, or expiry.",
      "A daily file cannot show whether a price came before or after a message. So every call is read three ways, and the results that depend on the reading are marked.",
      "Price data is kept 30 days behind today, as SEBI requires of tools that use market prices for investor education.",
    ],
    methodMore: "The full rules",
  },

  method: {
    title: "How a call is checked",
    lead: "Every rule the ledger applies, in the order it applies them. Nothing here is a judgement: it is arithmetic on the exchange's own prices.",
    rulesTitle: "The rules",
    rules: [
      ["Reading the message", "A message counts as a call when a stock or contract and at least one price can be read from it. The reader is a fixed set of rules, not a language model, so the same message always reads the same way. Messages it cannot read are counted and shown, never guessed."],
      ["Finding the contract", "An option is matched to its exact strike, type and expiry. With no expiry in the message, the nearest expiry on or after the call date is used; if the quoted price does not fit that contract's prices for the day, the next expiry that fits is used instead."],
      ["Entering", "The call is entered at the price the message quotes, but only if that price traded that day. \"Buy above 250\" starts when 250 trades. A quoted price outside the day's range means the call cannot be checked."],
      ["Leaving", "The call ends at its first target or its stop-loss, whichever the prices reach first. With neither, an option is held to expiry and settled at its value against the index or stock; a share is closed after ten trading days."],
      ["Money", "₹50,000 to start. ₹10,000 goes into each call: whole lots for options and futures, at least one. Brokerage, STT and exchange charges are taken off with a simple, stated model. When the account cannot pay for one lot, the call is not taken."],
    ],
    readingsTitle: "Three readings of the same day",
    readingsBody: "The exchange's daily file gives the day's open, high, low and close, not the order they came in. On the day a call is posted, the high may have printed before the message. So each call is replayed three ways.",
    readings: [
      ["Best", "Every doubtful touch is read in the channel's favour. No single call can have done better than this."],
      ["Worst", "A price counts only if it must have traded after the entry: the day closed beyond it, or the message came at the open and the price lies outside the open and the quoted entry."],
      ["Main figure", "A doubtful win counts when the channel announced it at the time and that day's prices do not contradict it. A doubtful stop-loss counts when the channel stayed silent."],
    ],
    chanceTitle: "The coin's hit rate",
    chanceBody: "A target 25% away with no stop-loss is reached about four times in five by a price that moves at random, because the only way to miss is to fall to zero first. The ledger works this out for the channel's own calls: for each, (entry − stop) ÷ (target − stop), with the stop at zero when none is given. A hit rate near that figure shows no skill. What matters then is what the misses cost.",
    dataTitle: "Where the numbers come from",
    data: [
      ["Share prices", "NSE cash-market bhavcopy, every trading day from 1 January 2024."],
      ["Options and futures", "NSE F&O bhavcopy, and BSE derivatives bhavcopy for SENSEX and BANKEX contracts."],
      ["Splits and bonuses", "Found from the price gap on the day they take effect; later prices are restated in the call's terms."],
      ["SEBI registration", "A dated copy of SEBI's public register of Research Analysts and Investment Advisers."],
      ["30-day lag", "Price data stops 30 days before the day the data was built. SEBI allows market prices in investor education only with that lag, so the newest calls show as too recent."],
    ],
    limitsTitle: "What it cannot do",
    limits: [
      "It cannot see inside a trading day. Results that depend on the order of prices within the day are marked, and the account is given as a range.",
      "It cannot read calls posted as pictures.",
      "It has no prices for commodities, currencies, crypto or foreign markets, and says so for each such call.",
      "It cannot read a channel whose public preview is switched off, except from an export file.",
      "Stock option contracts are not restated across a split or bonus.",
      "It cannot tell whether a follower could actually have bought at the quoted price, or how late they saw the message.",
      "The complaint draft and the call list are written in English only.",
      "It says nothing about what any stock or contract will do next, and never will.",
    ],
  },
  landing: {
    rail: ["The ledger", "One call", "The coin test", "The chat", "Three readings", "The pause", "Where to report"],
    scroll: "The evidence, exhibit by exhibit",

    oneCall: {
      tag: "Exhibit B · one call",
      title: "What the message said. What the exchange recorded.",
      step1: (date: string, time: string) => `${date} · ${time} · the message`,
      note1: "No stop-loss in the message. It is sold separately.",
      step2: "The same contract, day by day",
      target: "target",
      bought: "bought",
      expiry: "expiry",
      before: "before the call",
      step3: (date: string) => `${date} · settlement`,
      note3: (entry: string, target: string) => `Bought at ${entry}. Never reached ${target}. Expired at zero.`,
      sum: (qty: number, entry: string, costs: string) => `${qty} units × ₹${entry}, plus ${costs} in costs`,
    },

    coin: {
      tag: "Exhibit C · the coin test",
      title: "Would a coin have done better?",
      lead: "A target with no stop-loss is reached about three times in four by chance alone. A hit rate means nothing until it stands beside what a coin would manage with the same targets and stop-losses.",
      result: (below: number, total: number) => `${below} of ${total} real channels reached their targets less often than the coin.`,
      resultBest: (n: number) => `${n} stay below it even when every doubtful result is read in the channel's favour.`,
      xAxis: "what a coin would hit with the same targets and stop-losses →",
      yAxis: "what the channel hit →",
      diagonal: "as good as a coin",
      above: "Exhibit A",
      whisker: "dot: main figure · line: worst to best reading",
      foot: (read: number, total: number, min: number) => `${read} public channels read. The ${total} with ${min} or more replayed calls that carried a target are shown. Names withheld.`,
      caveat: "Beating the coin is not the same as making money. What the misses cost decides that.",
    },

    chat: {
      tag: "Exhibit D · the chat",
      title: (n: string) => `${n} messages. Not one about a loss.`,
      lead: "Every message the same channel posted, in the order it posted them. One square each.",
      kinds: { call: "calls", profit: "posts about points and profit", selling: "sales messages", loss: "posts about a loss", other: "everything else" },
      won: (a: number, b: number) => `${a} of ${b} winning calls were followed by a profit post`,
      lost: (a: number, b: number) => `${b} calls lost money. Posts that say so: ${a}`,
      stop: (a: number, b: number) => `${a} of ${b} calls gave no stop-loss. The message said "SL PAID"`,
    },

    readings: {
      tag: "Exhibit E · what a daily price cannot settle",
      title: "One day. Three honest readings.",
      lead: (date: string, time: string, contract: string, target: string) => `${date}, ${time}. The channel calls ${contract} with a target of ${target}. The exchange's file for that day gives the high as exactly ${target}.`,
      question: (time: string) => `Before ${time}, or after? A daily file does not say.`,
      bar: "the day's bar",
      ohlc: { o: "open", h: "high", l: "low", c: "close" },
      message: "message",
      pathA: "the high came before the message",
      pathB: "the high came after the message",
      illustration: "Two days that leave the same bar. The paths are drawn for illustration; the bar is the exchange's.",
      rows: {
        best: ["Best for the channel", "Every doubtful touch counts as reached."],
        worst: ["Worst for the channel", "A price counts only if it must have come after the call."],
        likely: ["Main figure", "A doubtful win counts only if the channel announced it at the time."],
      },
      quoted: (q: string) => `The channel's own updates that morning stopped at ${q}.`,
      close: "Every result like this is marked on the ledger, and the account is given as a range.",
    },

    pause: {
      tag: "Exhibit F · before the next call",
      title: "Twenty-four hours between the message and the money.",
      lead: "A tip arrives with a clock on it: now, fast, limited seats. The pause card sets a slower clock beside it.",
      lookFor: "Three things to look for in the message",
      questions: ["Is the stop-loss in the message, or sold separately?", "Is the sender on SEBI's register?", "What became of the last ten calls?"],
      card: "Pause card",
      record: "The channel's record",
      hit: (a: string, b: string) => `Reached target ${a} of the time. A coin would: ${b}.`,
      admitted: (lost: number, n: number) => `${lost} calls lost money. Posts that say so: ${n}.`,
      noStop: "The stop-loss is sold separately.",
      reasonLabel: "Why do you want to take this call?",
      placeholder: "Write it in your own words",
      start: "Start the 24 hours",
      running: "Read your reason again in",
      done: "24 hours have passed. Read your reason again.",
      reset: "Clear",
      saved: "Kept on this device only. Nothing is sent anywhere.",
    },

    where: {
      tag: "Exhibit G · where to report it",
      title: "Unregistered advice has an address.",
      lead: "Giving buy and sell calls for a fee needs a SEBI registration. Check the number a channel shows, then take the route that fits.",
      checkLabel: "Check a registration number",
      placeholder: "INH… or INA… number",
      check: "Check",
      bad: "A registration number looks like INH000001234 or INA000001234.",
      found: (no: string, name: string, from: string) => `${no} is on SEBI's register as "${name}", registered ${from}.`,
      notFound: (no: string) => `${no} is not on SEBI's register.`,
      asOf: (date: string) => `Register copied from sebi.gov.in on ${date}`,
      loading: "Opening the register",
      routes: [
        ["The channel is not registered", "SEBI Market Intelligence portal", "mi.sebi.gov.in", "https://mi.sebi.gov.in/"],
        ["Money has already been lost", "National Cyber Crime Reporting Portal, or call 1930", "cybercrime.gov.in", "https://cybercrime.gov.in/"],
        ["A registered analyst or adviser", "SEBI SCORES", "scores.sebi.gov.in", "https://scores.sebi.gov.in/"],
      ] as [string, string, string, string][],
      if: "If",
    },


    closing: {
      title: "Bring the channel you are about to pay for.",
      foot: "Reckoning looks at the past only. It says nothing about what any stock or contract will do next.",
      sources: "Prices: NSE and BSE daily bhavcopy. Register: sebi.gov.in.",
    },
  },
  caseFile: {
    nav: "A SEBI case",
    tag: "Case file",
    title: "The same checks, on a case SEBI has already examined.",
    lead: (date: string) => `On ${date} SEBI passed an interim order about stock recommendations posted on social media. Annexure A of the order lists the recommendations behind the money it impounded. We ran this site's pattern checks on those dates, and on ordinary days in the same stocks.`,
    caution: "An ex-parte interim order records what SEBI found on a first view. It is not a final finding against anyone, and no person is named on this page.",
    orderRef: "Order",
    impounded: "Impounded by the order",
    recos: "Recommendations in Annexure A",
    measured: "Inside our price files",
    coverage: (measured: number, total: number, stocks: number, from: string) => `${measured} of the ${total} recommendations, in ${stocks} stocks, fall inside our price files (NSE, from ${from}). The rest are in stocks that trade only on BSE, or are older than the data.`,
    ratesTitle: "How often each pattern appears",
    onRecos: "after the order's recommendations",
    onOrdinary: "on ordinary days in the same stocks",
    patterns: {
      spike: ["Jumped on heavy volume", "Up 8% or more within two trading days, on three times normal volume or more."],
      pump: ["Jumped, then fell back", "The same jump, followed by a fall of 15% or more from the peak within ten trading days."],
      preRun: ["Already running before the post", "Up 10% or more in the five trading days before, on three times normal volume or more."],
      thin: ["Thinly traded", "Less than ₹25 lakh changing hands on a normal day."],
    },
    times: (x: string) => `${x} times as often`,
    notMore: "No more often than on ordinary days. This check did not pick these stocks out.",
    smeLine: (n: number, total: number) => `${n} of the ${total} measured recommendations were in SME-platform stocks.`,
    chartsTitle: "Three of the stocks",
    chartsLead: "Closing price and volume. Each red line is a recommendation listed in the order.",
    recoCount: (n: number) => `${n} recommendations`,
    tableTitle: "Every recommendation measured",
    cols: { day: "First trading day", stock: "Stock", up: "Up within 2 days", volume: "Volume", fall: "Then fell", marks: "Patterns" },
    sme: "SME",
    showAll: (n: number) => `Show all ${n}`,
    source: "Source: SEBI order, Annexure A, pages 198 to 234. Prices: NSE daily bhavcopy.",
    openOrder: "Open the order on sebi.gov.in",
  },

  // What the engine says about one call. It records which sentence and the figures in it; prices arrive written
  // out ("₹420"), dates already in the reader's language.
  notes: {
    // why a call could not be checked
    notTradedDay: "This contract did not trade on the day of the call, so there is no price to check it against.",
    noEntryIntraday: "The message gives no entry price. An intraday call without one cannot be placed on daily prices.",
    levelNotReached: (level: string, days: number) => `The entry level ${level} did not trade within ${days === 1 ? "the day" : `${days} trading days`} of the call.`,
    priceOutside: (quoted: string, low: string, high: string) => `The quoted price ${quoted} is outside what this contract traded that day (${low} to ${high}). The message may refer to a different contract.`,
    noUsableEntry: "No usable entry price on that day.",
    indexAmbiguous: "The message does not name the index, and the quoted price fits more than one.",
    indexNoFit: "The message does not name the index, and no index contract with this strike traded at the quoted price that day.",
    tooRecent: (lagDays: number, to: string) => `Too recent to check. Price data for investor education carries a ${lagDays}-day lag, so prices are available up to ${to}.`,
    beforeData: (from: string) => `The call is dated before the price data starts (${from}).`,
    offExchange: (symbol: string, exchange: string) => `${symbol} trades on ${exchange}, which this price data does not cover.`,
    offCrypto: (symbol: string) => `${symbol} trades on a crypto exchange, which this price data does not cover.`,
    offAbroad: (symbol: string) => `${symbol} trades on a market outside India, which this price data does not cover.`,
    notInCash: (symbol: string) => `${symbol} is not a stock in the NSE cash market data.`,
    noDerivatives: (symbol: string) => `${symbol} has no futures or options on NSE in the data.`,
    noFuture: (symbol: string) => `No ${symbol} futures contract found for that date.`,
    noStrike: "The message does not give a strike and CE/PE.",
    stockOptionsFrom: (from: string) => `Stock option prices are included from ${from} only.`,
    noOptionExpiry: (symbol: string) => `No ${symbol} option expiry found for that date.`,
    optionNotTraded: (contract: string) => `${contract} did not trade in any expiry near the call date.`,

    // what was assumed in replaying it
    nextTradedDay: "No trades on the day of the call; replayed from the next day it traded.",
    enteredAtClose: "No entry price in the message; entered at that day's closing price.",
    enteredAtNextOpen: "No entry price in the message; entered at the next opening price.",
    openedPast: "Price opened past the entry level; entered at the open.",
    quotedNotTraded: (quoted: string) => `The quoted price ${quoted} did not trade the next day; entered at the open.`,
    targetIgnored: "Stated target is not beyond the entry price; ignored.",
    stopIgnored: "Stated stop-loss is not on the losing side of the entry price; ignored.",
    firstTarget: "First target counts as the exit.",
    noPeriodShare: (days: number) => `No holding period stated; closed after ${days} trading days if neither level is touched.`,
    noPeriodContract: "No holding period stated; held until a level is touched or the contract expires.",
    bothSameDay: "Target and stop-loss both traded on the same day; daily prices cannot show which came first.",
    targetDoubtful: "The target price traded that day; daily prices cannot show whether that was before or after the message. Read in the channel's favour.",
    stopDoubtful: "The stop-loss price traded that day; daily prices cannot show whether that was before or after the message. Read against the channel.",
    settledAtExpiry: "The contract stopped trading before expiry; settled at its expiry value.",
    closedAtLastPrice: "The contract stopped trading before expiry; closed at its last traded price.",
    stillRunning: "Still running when the price data ends; valued at the last closing price.",
    noTradesLastDay: "No trades on the last day of the holding period; closed at the last traded price.",
    indexInferred: (index: string) => `The message does not name the index; ${index} is the only one where this strike traded at the quoted price that day.`,
    restated: "A split or bonus took effect after the call; later prices are restated in the call's terms.",
    indexAsFuture: "An index level cannot be bought; replayed on the near-month future.",
    nextExpiryFits: "The quoted price does not fit the nearest expiry; the next expiry that it fits was used.",
    nearestExpiry: "No expiry in the message; the nearest expiry on or after the call date was used.",
    heldToExpiry: "Held to expiry: settled at the option's value against the underlying's closing level.",

    // what was unusual about the message itself
    readAs: (written: string, symbol: string) => `"${written}" read as ${symbol}.`,
    firstContract: "More than one contract in the message; the first one was read.",
    indexUnnamed: "The message does not name the index.",
    partName: "Stock matched from part of its company name.",
    stopZero: "Stop-loss stated as zero: the whole amount is at risk.",
    noAction: "The message does not say buy or sell.",
    noEntry: "No entry price in the message.",
    noLevels: "No target or stop-loss in the message.",
    targetWrongSide: "The target is not beyond the entry price for this direction.",
    stopWrongSide: "The stop-loss is not on the losing side of the entry price.",
    fromEarlier: "Instrument taken from the message this one follows.",
    edited: "The message was edited after it was posted.",
  },
};

export type Strings = typeof en;
